Repository AY2324S2-CS2113-F14-4/tp, pull requests merged in 2024-04, with the labels that each got.

#74 As a user, I want to visualize my transactions graphically when viewing history ...
  src/main/java/command/ViewHistoryCommand.java
  src/main/java/financeproject/data/Bob.txt
Labels: type.Story, Priority:Medium

#75 Implement sorting of transaction list by time
  data/Bob.txt
  src/main/java/command/AddInflowCommand.java
  src/main/java/command/AddOutflowCommand.java
  src/main/java/financeproject/Main.java
  src/main/java/financeproject/data/data.txt
  src/main/java/financialtransactions/Transaction.java
  src/main/java/financialtransactions/TransactionComparator.java
  src/main/java/financialtransactions/TransactionList.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/template/BaseDate.java
  src/test/java/parser/ParserTest.java
Labels: enhancement, priority.High

#76 Create IncorrectCommandSyntaxException
  src/main/java/command/AddInflowCommand.java
  src/main/java/command/AddOutflowCommand.java
  src/main/java/command/AddReminderCommand.java
  src/main/java/command/DeleteInflowCommand.java
  src/main/java/command/DeleteOutflowCommand.java
  src/main/java/command/DeleteReminderCommand.java
  src/main/java/command/EditInflowCommand.java
  src/main/java/command/EditOutflowCommand.java
  src/main/java/command/EditReminderCommand.java
  src/main/java/command/SetBudgetCommand.java
  src/main/java/command/ViewHistoryCommand.java
  src/main/java/customexceptions/IncorrectCommandSyntaxException.java
  src/main/java/financeproject/Main.java
  src/main/java/financeproject/data/Bob.txt
Labels: priority.High, type.Task

#77 Create CategoryNotFoundException
  src/main/java/command/AddInflowCommand.java
  src/main/java/command/AddOutflowCommand.java
  src/main/java/command/AddReminderCommand.java
  src/main/java/command/BaseCommand.java
  src/main/java/command/EditInflowCommand.java
  src/main/java/command/EditOutflowCommand.java
  src/main/java/command/EditReminderCommand.java
  src/main/java/customexceptions/CategoryNotFoundException.java
  src/main/java/financeproject/data/Bob.txt
  src/main/java/financialtransactions/Inflow.java
  src/main/java/financialtransactions/Outflow.java
  src/main/java/financialtransactions/Reminder.java
  src/main/java/financialtransactions/Transaction.java
  src/main/java/storage/Storage.java
  src/test/java/financialtransactions/InflowTest.java
  src/test/java/financialtransactions/OutflowTest.java
  src/test/java/financialtransactions/TransactionManagerTest.java
  src/test/java/seedu/OutflowTest.java
Labels: priority.High, type.Task

#78 Update UG based on v1.0 features
  docs/UserGuide.md
Labels: documentation

#80 Update UserGuide with undo, bar chart and timer
  docs/UserGuide.md
Labels: priority.High

#79 Update UG for v2.0 features
  docs/UserGuide.md
Labels: documentation

#83 Update UG
  docs/UserGuide.md
Labels: documentation

#127 Reposition timer object for each command class
  src/main/java/command/AddInflowCommand.java
  src/main/java/command/AddOutflowCommand.java
  src/main/java/command/AddReminderCommand.java
  src/main/java/command/BaseCommand.java
  src/main/java/command/DeleteInflowCommand.java
  src/main/java/command/DeleteOutflowCommand.java
  src/main/java/command/DeleteReminderCommand.java
  src/main/java/command/UndoCommand.java
  src/main/java/parser/Parser.java
  src/main/java/storage/BarChart.java
  src/main/java/user/InactivityTimer.java
Labels: Priority:Medium, type.Task

#128 Resolve Issue #100
  docs/team/chongxern.md
  src/main/java/command/ViewHistoryCommand.java
Labels: bug

#129 Update chongxern.md Project Portfolio Page
  docs/team/chongxern.md
Labels: documentation

#132 Add Kishen271828 contribution in PPP
  docs/team/kishen271828.md
Labels: documentation

#134 Fix issues #126, #104 and #95
  src/main/java/command/ViewHistoryCommand.java
  src/main/java/financialtransactions/TransactionManager.java
Labels: bug, Priority:Medium

#137 Fix Issue #115
  src/main/java/command/DeleteReminderCommand.java
Labels: bug, priority.Low

#140 Merge branch-undo with main branch
  src/main/java/command/AddInflowCommand.java
  src/main/java/command/AddOutflowCommand.java
  src/main/java/command/AddReminderCommand.java
  src/main/java/command/BaseCommand.java
  src/main/java/command/DeleteInflowCommand.java
  src/main/java/command/DeleteOutflowCommand.java
  src/main/java/command/DeleteReminderCommand.java
  src/main/java/command/EditInflowCommand.java
  src/main/java/command/EditOutflowCommand.java
  src/main/java/command/EditReminderCommand.java
  src/main/java/command/ExitCommand.java
  src/main/java/command/GenerateReportCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/SetBudgetCommand.java
  src/main/java/command/UndoCommand.java
  src/main/java/command/ViewHistoryCommand.java
  src/main/java/customexceptions/CategoryNotFoundException.java
  src/main/java/customexceptions/UndoNotPermittedException.java
  src/main/java/financeproject/Main.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/user/InactivityTimer.java
Labels: priority.High, type.Task

#145 Fix undo for delete commands, disable undo for edit commands
  src/main/java/command/UndoCommand.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/parser/Parser.java
Labels: priority.High

#146 Remove unnecessary print lines
  src/main/java/command/DeleteInflowCommand.java
  src/main/java/financeproject/data/Bob.txt
Labels: priority.Low

#147 Update TransactionManager.java
  src/main/java/financialtransactions/TransactionManager.java
Labels: bug, priority.High
