Repository AY2324S2-CS2113-F14-4/tp, pull requests merged in 2024-03, with the labels that each got.

#26 Add an AddInflow method
  src/main/java/financialtransactions/Transaction.java
  src/main/java/financialtransactions/TransactionList.java
  src/test/java/financialtransactions/InflowTest.java
  src/test/java/seedu/OutflowTest.java
Labels: type.Task

#31 Add protected print method
  src/main/java/financialtransactions/TransactionList.java
Labels: priority.High, type.Task

#34 Change remove transaction for inflow and outflow
  data/data.txt
  src/main/java/financeproject/Main.java
  src/main/java/financialtransactions/Inflow.java
  src/main/java/financialtransactions/Outflow.java
  src/main/java/financialtransactions/Transaction.java
  src/main/java/financialtransactions/TransactionList.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/parser/Parser.java
Labels: type.Task

#40 Adjust exceptions for timeout and typo, and add taxes
  src/main/java/customexceptions/InactivityTimeoutException.java
  src/main/java/customexceptions/IncompletePromptException.java
  src/main/java/customexceptions/SecurityException.java
  src/main/java/financeproject/Main.java
  src/main/java/financialtransactions/Outflow.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/parser/Parser.java
  src/main/java/user/InactivityTimer.java
  src/test/java/parser/ParserTest.java
Labels: priority.High, type.Task

#42 Fix bugs from previous merge
  data/data.txt
  src/main/java/command/BaseCommand.java
  src/main/java/financeproject/Main.java
  src/main/java/financialtransactions/Outflow.java
Labels: type.Task

#45 Resolve exception handling for incomplete prompt, remove parser test, fix taxes for transaction manager test
  data/data.txt
  src/main/java/customexceptions/IncompletePromptException.java
  src/main/java/financeproject/Main.java
  src/main/java/financialtransactions/Outflow.java
  src/main/java/parser/Parser.java
  src/main/java/user/InactivityTimer.java
  src/test/java/financialtransactions/TransactionManagerTest.java
  src/test/java/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#49 Fix storage issues, modify help command
  src/main/java/command/AddOutflowCommand.java
  src/main/java/command/DeleteInflowCommand.java
  src/main/java/command/DeleteOutflowCommand.java
  src/main/java/command/EditInflowCommand.java
  src/main/java/command/EditOutflowCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/financeproject/Main.java
  src/main/java/financialtransactions/TransactionList.java
  text-ui-test/input.txt
Labels: priority.High

#47 Adjust security exception, move tax to category
  src/main/java/command/AddInflowCommand.java
  src/main/java/customexceptions/ExceededAttemptsException.java
  src/main/java/customexceptions/IncompletePromptException.java
  src/main/java/customexceptions/SecurityException.java
  src/main/java/financeproject/Main.java
  src/main/java/financeproject/data/data.txt
  src/main/java/financialtransactions/Outflow.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/parser/Parser.java
  src/main/java/user/Authentication.java
  src/main/java/user/InactivityTimer.java
  src/test/java/financialtransactions/OutflowTest.java
  src/test/java/financialtransactions/TransactionManagerTest.java
  src/test/java/user/BaseUserTest.java
Labels: priority.High, type.Task

#54 Add maximum description length to ensure description is not too long
  src/main/java/financeproject/data/data.txt
  src/main/java/financialtransactions/Transaction.java
Labels: priority.Low, type.Task

#55 Developer guide: Implementation details of view transaction history feature
  docs/DeveloperGuide.md
  src/main/java/command/AddInflowCommand.java
  src/main/java/command/AddOutflowCommand.java
  src/main/java/command/ViewHistoryCommand.java
  src/main/java/parser/Parser.java
  src/test/java/parser/ParserTest.java
Labels: documentation

#57 Update DevelopersGuide.md to include a few of the upcoming proposed features
  docs/DeveloperGuide.md
Labels: Priority:Medium

#58 Enable assertions for build.gradle
  build.gradle
Labels: Priority:Medium

#60 Add sorting by name comparator method for sorting transactions
  src/main/java/financeproject/data/data.txt
  src/main/java/financialtransactions/Transaction.java
  src/main/java/financialtransactions/TransactionList.java
  src/main/java/financialtransactions/TransactionManager.java
  src/main/java/template/BaseDate.java
Labels: Priority:Medium, type.Task

#64 Create BarChart class
  src/main/java/financialtransactions/Outflow.java
  src/main/java/storage/BarChart.java
Labels: Priority:Medium, type.Task
